### ISSUE TITLE
Error in console, causing major lag (using latest dev build)

### ISSUE THREAD

**Issue by ghost** [mrlolethan/NexGen-KoTHs#2]
java.lang.NullPointerException
        at com.mrlolethan.nexgenkoths.scoreboard.NexGenBoard.update(Unknown Source) ~[?:?]
        at com.mrlolethan.nexgenkoths.scoreboard.ScoreboardHandler$1.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-081dfa5-7658819]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-081dfa5-7658819]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot.jar:git-Spigot-081dfa5-7658819]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-081dfa5-7658819]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-081dfa5-7658819]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-081dfa5-7658819]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by EthanJoyce** [comment]
A full rewrite of this project is in progress.
